### PR TITLE
upgrade for tf1.0

### PR DESCRIPTION
**Pull request by philokey**
execute [tf_upgrade.py](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility)

### CODE REVIEW

**Comment by endernewton** [comment]
Thanks! I will leave it open just in case people are still using older versions.

**Comment by philokey** [comment]
@endernewton OK. By the way, do you plan to add Resnet to the faster rcnn?

**Comment by endernewton** [comment]
I want to but do not have much time now. Plan to do that in April/May. But if you are interested, you can try on your end and submit another PR.

**Comment by philokey** [comment]
@endernewton I add python3 support and reformat the code from faster-rcnn to [tensorflow style](https://www.tensorflow.org/community/style_guide), which use 2 space tab.

**Comment by philokey** [comment]
@endernewton add resnet101

**Comment by endernewton** [comment]
Nice! Can you train the models and see what numbers can you get? Let's make
them comparable to the numbers reported in here
<https://arxiv.org/abs/1612.03144> (they did change some of it, like batch
size, proposal scales, image resolution, etc).

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA

**Comment by philokey** [comment]
@endernewton I have finished  experiments in PASCAL VOC07, I will I update README to report the numbers. The model in coco is training and results of coco will come out in a few days.

**Comment by philokey** [comment]
update readme

**Comment by endernewton** [comment]
@philokey Wow! I will reformat the README so that the result section is not too lengthy.. Please take your time in trying COCO etc. Also I guess it would be great to add links to the pre-trained ResNet101 and your best model on VOC/COCO (email me if you want me to upload on our server etc), and add some comments to the added code, so that other people can use it. Thanks!!

**Comment by endernewton** [comment]
Also I have left the detailed numbers for VOC and my numbers on COCO minival. There seems to be a typo for the boat AP and the table seems too wide to fit into a screen..

**Comment by philokey** [comment]
I will send the result to you by email.

**Comment by endernewton** [comment]
Cool! I see you have another ckpt for imagenet VGG16 as well, could you
point out the link to that? Also the link to the Resnet pretrained model.
:) Appreciate it!

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA

**Comment by endernewton** [comment]
Oh I find it! No need to point it out then. :)

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA

**Comment by endernewton** [comment]
Pushed an updated version, with minor change in the roi pooling layer that removes maxpool. Since resnet101 does not have maxpool before feeding to the next layers. Updated experimental results needed though.

**Pull request merged**
