### PR TITLE
adds architecture for grid k520, tesla k80 gpus

### PR DESCRIPTION
**Pull request by SnShine**

### CODE REVIEW

**Comment by endernewton** [comment]
thanks! did you test it with both training and testing?

**Comment by SnShine** [comment]
Only testing. Anyway, I am going to train asap. Will modify if necessary.

**Comment by endernewton** [comment]
thanks!

**Comment by SnShine** [comment]
I have tested k80 for training and inference and grid k520 for only inference as it has only 4gb memory. I guess you can merge it.

**Pull request merged**
